This is a info ....
This is a error...
This is a info ....
This is a error...



This is a info ....
This is a error...
This is a info ....
This is a error...



This is a info ....
This is a error...
This is a info ....
This is a error...
This is a info ....
This is a error...



2020-06-03 21:23:21,047 - __main__ - INFO - this is a test from info
2020-06-03 21:23:21,047 - __main__ - WARNING - This is a test from warning
2020-06-03 21:23:21,047 - __main__ - INFO - Finish
2020-06-03 21:23:21,048 - __main__ - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "K:/myprogram/pyprogram/day17/logging.trace.py", line 33, in <module>
    open("sklearn.txt","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'sklearn.txt'
2020-06-03 21:23:21,049 - __main__ - INFO - Finish
2020-06-03 21:24:30,875 - __main__ - INFO - this is a test from info
2020-06-03 21:24:30,875 - __main__ - WARNING - This is a test from warning
2020-06-03 21:24:30,875 - __main__ - INFO - Finish
2020-06-03 21:24:30,876 - __main__ - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "K:/myprogram/pyprogram/day17/logging.trace.py", line 33, in <module>
    open("sklearn.txt","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'sklearn.txt'
2020-06-03 21:24:30,876 - __main__ - INFO - Finish
